services:
  - type: web
    name: fixio-enterprise
    env: python
    buildCommand: "cd frontend && npm install && CI=false npm run build && cd .. && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MONGO_URI
        sync: false
